### ISSUE TITLE
[WIP] Predicate Notation Version 2

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-predicates#41]
## Overview

Derived from https://github.com/cryptoeconomicslab/plasma-predicates/issues/31

## What problem can be solved

The problem can be solved is same as the previous version, but this version is more general.

> It's hard to explain new predicate each time is created. Researchers need very high context background to understand the behavior of deprecation logic in the discussion. ex) plasma.build We define the notation for predicates to define and share a new predicate quickly and correctly.

### Dispute scheme and deprecation logic

* The dispute scheme is to prove the validity of state.
* The deprecation logic is to prove deprecation of state.

```
dispution(state, deprecation logic).
```

### Theorem

```python
dispution(deprecationA(state) and deprecationB(state)) = dispution(deprecationA(state)) or dispution(deprecationB(state))
dispution(deprecationA(state) or deprecationB(state)) = dispution(deprecationA(state)) and dispution(deprecationB(state))
```
#### Fee predicate

This formula defamation stands for that fee transfer predicate can be split into fee predicate and ownership predicate.

```
predicate(proveFee(state) and proveDeprecation(state))
= predicate(proveFee(state)) or predicate(proveDeprecation(state))
```

```
1. predicate(proveFee(state) and proveDeprecation(state))
```

1. means one predicate has the deprecation logic which is combined from proveFee and proveDeprecation.

```
2. predicate(proveFee(state)) or predicate(proveDeprecation(state))
```

2. means that two exits run at the same time and if at least one exit succeed the whole state should be exitable.

#### Simple swap predicate

```
predicate(proveDeprecation(state) and (proveInclusion(state.correspondent) or confirmation(state.correspondent))) or predicate(proveInclusion(state.correspondent) and confirmation(state.correspondent))
= predicate(proveDeprecation(state)) or predicate(proveInclusion(state.correspondent) and confirmation(state.correspondent))
= predicate(proveDeprecation(state)) or predicate(proveInclusion(state.correspondent)) or predicate(confirmation(state.correspondent))
```

#### Payment channel predicate

```
predicate(proveClose(openState)) and channel(deprecation(openState))
```

#### Dex predicate

```
predicate(proveDeprecation(state)) or (predicate(finalizeExit(state.correspondent)) and predicate(proveDeprecation(state.correspondent)))
```

## What topic to research next

**Comment by weili-go** [comment]
This is too abstract, can't resonate, can you give some simple examples?

**Comment by syuhei176** [comment]
This issue was out of dated.
We will use OVM and predicate 2.0 described in these articles and we'll also make examples. 
https://medium.com/plasma-group/introducing-the-ovm-db253287af50
https://hackmd.io/@aTTDQ4GiRVyyce6trnsfpg/S1yGmXVxB

We'll write blog post about our development direction in this week.

**Comment by weili-go** [comment]
Very nice.
Thanks.
